[WIP] Qiita login
increments/mastodon pull request #8
Opened 2017-05-07 14:39 UTC by tomoasleep

QiitaのOAuthを利用してアカウント作成とログインが行えるようにする。

<img width="659" alt="2017-05-07 23 38 05" src="https://cloud.githubusercontent.com/assets/1477130/25782083/4158dee2-337e-11e7-83a1-5124887fc06d.png">

2017-05-11 10:18 UTC, tomoasleep commented
@takashi @yujinakayama レビューお願いします :pray:

2017-05-12 03:09 UTC, tomoasleep commented
@takashi の助言でCookieStoreにAuthHash保存するようにした。

2017-05-15 12:41 UTC, tomoasleep commented
そういえば、メール認証をしないとログインできないので新規登録までに、

1. Qiitaで参加ボタンを押す
2. 新規登録フォームでユーザーネームとメールアドレスを送信する
3. メール認証をする
4. Qiitaで参加ボタンを押してログイン

…と使えるようになるまでに2回Qiitaで参加ボタンを押す必要があるのが面倒だ…

2017-05-16 06:18 UTC, takashi requested changes

2017-05-16 06:18 UTC, takashi commented on app/models/oauth_authorization.rb
> +class OauthAuthorization < ApplicationRecord
OauthAuthorization という名前、 Authorization と2回行っているようで不自然なのと、 Oauth(という仕様)とのAuthorization のようにとれ、違和感があります。

この場合 Qiita との Authorization なわけなので、QiitaAuthorization とするのはどうでしょうか

2017-05-16 06:18 UTC, takashi commented on app/models/form/oauth_registration.rb
> +      password: password,
ここで password をユーザの代わりに追加しているけど、このパスワードはユーザーに知らされる？

2017-05-16 06:18 UTC, takashi commented on app/controllers/auth/omniauth_callbacks_controller.rb
> +    session[:devise_omniauth_auth] = request.env['omniauth.auth'].to_json,
cookie store を使用しているならば、serializer を `marshal` にしていても `json` にしていても hash はそのまま格納できるはずです。 to_json 必要なさそう

2017-05-17 06:04 UTC, tomoasleep commented on app/models/form/oauth_registration.rb
> +      password: password,
知らされないので、パスワードを再発行するまでパスワード認証は実質利用できない状態です。

2017-05-18 02:32 UTC, tomoasleep commented on app/models/form/oauth_registration.rb
> +      password: password,
`dummy_password_flag` を足して初回だけ現在のパスワードを入力しなくてもパスワードを変更できるようにした

初回のみ現在のパスワードを入力するinputを非表示にしている。

<img width="744" alt="2017-05-18 11 01 44" src="https://cloud.githubusercontent.com/assets/1477130/26184014/440f6e52-3bbd-11e7-8268-36fdc5562ace.png">

2017-05-18 10:50 UTC, tomoasleep commented on app/models/form/oauth_registration.rb
> +      password: password,
<img width="521" alt="2017-05-18 19 49 01" src="https://cloud.githubusercontent.com/assets/1477130/26198943/2166d282-3c03-11e7-8fcf-c4fcccf0ccc4.png">

最初にパスワードを変更する場合だけ `新しい` じゃなくした

2017-05-18 11:01 UTC, tomoasleep commented
# 新規登録の認証の仕様の変更

現在の仕様だと、Qiitaアカウントで新規登録してログインした状態になるまで都度2回QiitaのOAuthの認可画面を表示する必要があるので、新規登録してから1日の間はメール認証しなくてもログイン出来るように仕様を変更する。その場合、画面上部にアラートが表示される。

<img width="1302" alt="2017-05-18 17 08 57" src="https://cloud.githubusercontent.com/assets/1477130/26199281/62dfafda-3c04-11e7-96ec-82cc8bfbc938.png">

2017-05-18 11:04 UTC, tomoasleep commented
# 負荷対策用の、新規登録の制限

(負荷対策のために、)管理画面からQiita連携以外での新規登録を停止することも出来るようにする。

<img width="545" alt="2017-05-18 19 06 44" src="https://cloud.githubusercontent.com/assets/1477130/26199088/b42488c6-3c03-11e7-9b3f-7a02fce5fcfd.png">
<img width="740" alt="2017-05-18 19 52 22" src="https://cloud.githubusercontent.com/assets/1477130/26199099/c079b6e6-3c03-11e7-8d7d-e3fc7a389299.png">

2017-05-18 11:56 UTC, tomoasleep commented
@takashi 再度レビューお願いします

2017-05-18 12:55 UTC, takashi requested changes

2017-05-18 12:55 UTC, takashi commented on app/controllers/auth/omniauth_callbacks_controller.rb
> +class Auth::OmniauthCallbacksController < Devise::OmniauthCallbacksController
今更なのですが、 ここで行っているのは結局 QiitaAuthorization モデルの作成ですし、Setting の方も QiitaAuthorizationsController なので`Auth::QiitaAuthorizationsController` が適当なのではないかと思います 🙇

2017-05-18 12:55 UTC, takashi commented on app/assets/javascripts/components/features/ui/components/alert_bar.jsx
> +  isEmailConfirmed: PropTypes.bool,
これは require 属性をつけなくても大丈夫ですか？

2017-05-18 12:55 UTC, takashi commented on app/assets/javascripts/components/features/ui/components/alert_bar.jsx
> +              <i className='fa fa-fw fa-exclamation-triangle' /><FormattedMessage id='alert_bar.email_confirm_alert' defaultMessage='Your email address is not confirmed. Please confirm the sent email
`defaultMessage` が使われるのはどのようなケースですか？

2017-05-18 12:55 UTC, takashi commented on app/controllers/auth/omniauth_callbacks_controller.rb
> +        redirect_to settings_qiita_authorizations_path
インデントが1つ深いかも

2017-05-18 12:55 UTC, takashi commented on app/controllers/auth/omniauth_callbacks_controller.rb
> +    if current_user
この 「current_user が存在した場合」というのは 既存の password 認証のアカウントに Qiita アカウントに紐付ける というプロセスなので、今すぐには必要ない部分ですか？(消す必要はないと思っているが確認です)

2017-05-18 14:24 UTC, tomoasleep commented on app/controllers/auth/omniauth_callbacks_controller.rb
> +    if current_user
はい、現状使われることはない部分です 🙆

2017-05-18 14:32 UTC, tomoasleep commented on app/assets/javascripts/components/features/ui/components/alert_bar.jsx
> +              <i className='fa fa-fw fa-exclamation-triangle' /><FormattedMessage id='alert_bar.email_confirm_alert' defaultMessage='Your email address is not confirmed. Please confirm the sent email
Mastodonはja, en以外のlocaleを用意していて、その場合に使われます。

<img width="650" alt="2017-05-18 23 30 35" src="https://cloud.githubusercontent.com/assets/1477130/26207355/3e9c0ab0-3c22-11e7-912e-fba13ad7c50e.png">

2017-05-18 14:35 UTC, tomoasleep commented on app/assets/javascripts/components/features/ui/components/alert_bar.jsx
> +  isEmailConfirmed: PropTypes.bool,
付けといたほうが良さそうですね、thx 🙇

2017-05-18 14:49 UTC, tomoasleep commented on app/controllers/auth/omniauth_callbacks_controller.rb
> +class Auth::OmniauthCallbacksController < Devise::OmniauthCallbacksController
QiitaAuthorizationsを確かに作成してはいるのですが、どちらかと言うとここはDeviseの提供する仕組みの上でOmniauthのcallbackを処理する性格のほうが強いので、Deviseの命名に寄せていた方が良いと考えているのですが、どう思いますか？

2017-05-18 14:50 UTC, tomoasleep commented on app/controllers/auth/omniauth_callbacks_controller.rb
> +        redirect_to settings_qiita_authorizations_path
:flushed:

2017-05-19 02:54 UTC, tomoasleep commented
@takashi 修正 or コメントしたので再度レビューお願いします :pray:

2017-05-19 11:58 UTC, takashi commented on app/controllers/auth/omniauth_callbacks_controller.rb
> +class Auth::OmniauthCallbacksController < Devise::OmniauthCallbacksController
Omniauthのcallbackを処理するが、実際には Oauth Server 側 (今回だとQiita) で明示的にResource Owner のリソースを OauthClient 受け渡すための callback url を記述しているので、omniauth という gem が提供している仕組みではあるが  QiitaAuthorization を作成する、という考え方がしっくりくるのかな、と思った。
けど特に強い意見があるわけではないのでこのままでも大丈夫です 🙆‍♂️

2017-05-19 11:59 UTC, takashi commented on app/controllers/auth/omniauth_callbacks_controller.rb
> +class Auth::OmniauthCallbacksController < Devise::OmniauthCallbacksController
補足すると、 `qiita` というアクションに違和感があって、 アクションは原則 crud のみで構成されるべき、という rails の controller の実装的にこうすればいいんじゃないか、とおもった、というのもあります

2017-05-19 12:01 UTC, takashi commented on app/assets/javascripts/components/locales/ja.jsx
> +  "alert_bar.email_confirm_alert": "メールアドレスの確認が完了していません。登録したアドレス宛に送信されたメールを確認してください。",
1日の期限をもってログインできなくなるよ、という旨をここで書いたほうが親切かなと思ったけどどうでしょう？

2017-05-19 12:12 UTC, tomoasleep commented on app/assets/javascripts/components/locales/ja.jsx
> +  "alert_bar.email_confirm_alert": "メールアドレスの確認が完了していません。登録したアドレス宛に送信されたメールを確認してください。",
確かにそうですね👍

2017-05-22 00:49 UTC, tomoasleep commented on app/controllers/auth/omniauth_callbacks_controller.rb
> +class Auth::OmniauthCallbacksController < Devise::OmniauthCallbacksController
>  qiita というアクションに違和感があって、 アクションは原則 crud のみで構成されるべき、という rails の controller の実装的にこうすればいいんじゃないか

これはたしかにそうだと思いますが、今回は素直に提供する仕組みに乗っかって様子見ようと思います。forkなので。

2017-05-22 04:55 UTC, tomoasleep commented on app/assets/javascripts/components/locales/ja.jsx
> +  "alert_bar.email_confirm_alert": "メールアドレスの確認が完了していません。登録したアドレス宛に送信されたメールを確認してください。",
<img width="1341" alt="2017-05-22 13 54 42" src="https://cloud.githubusercontent.com/assets/1477130/26293128/41625778-3ef6-11e7-91ad-4b5edf631107.png">
直した ✌️

2017-05-22 05:16 UTC, takashi commented on app/controllers/auth/omniauth_callbacks_controller.rb
> +class Auth::OmniauthCallbacksController < Devise::OmniauthCallbacksController
okです 👌

2017-05-22 05:17 UTC, takashi approved these changes
LGTM

2017-05-22 05:19 UTC, tomoasleep commented
@takashi レビューthx 🙏

2017-05-22 05:19 UTC, merged